version: '3'

services:
  api:
    container_name: amp_api
    build:
      context: .
      dockerfile: Dockerfile
    
    environment:
      - API_PORT=$API_PORT

    ports:
      - "$API_PORT:$API_PORT"

    networks:
      - api_network

networks:
  api_network: